### PR TITLE
CudaText has Perl 6 lexer too

### PR DESCRIPTION
**Pull request by Alexey-T**

### CODE REVIEW

**Comment by lizmat** [comment]
I can't seem to find any reference about Perl 6 at that site.  Could you tell me where Perl 6 support is documented?

**Comment by vrurg** [comment]
@lizmat http://uvviewsoft.com/cudatext/download.html

**Comment by JJ** [comment]
Cool!

**Comment by lizmat** [comment]
@vrurg @JJ then I suggest we merge?

**Comment by AlexDaniel** [comment]
More editors are listed here: https://github.com/perl6/user-experience/issues/19

Should we list all of them?

**Comment by vrurg** [comment]
@AlexDaniel absolutely, unless @JJ objects.

**Comment by JJ** [comment]
Thanks!

**Pull request merged**
