### PR TITLE
New Design

### PR DESCRIPTION
**Pull request by zoffixznet**
This PR makes perl6.org a Bootstrap3/jQuery-based, themable website.

### Demo
The demo of what the site will look like, once merged, can be viewed at http://perl6.xtatik.org/

### CODE REVIEW

**Comment by moritz** [comment]
:+1: 
If nobody raises any concerns or objects very soon, I'll merge this.

**Comment by labster** [comment]
... but how will we attract 9 year old girl programmers without the bright colors?

Yeah, as much as it the word really needs yet another Bootstrap site, :+1:

Also the 6 is falling off the edge of the download button at smaller window widths.

**Comment by jonathanstowe** [comment]
I actually quite like it, but I shouldn't be considered anything like an authority on good web design.

I do think, however, that using a  fairly trendy CSS/Javascript framework like Bootstrap might encourage contributions :) Or has everyone moved on to Polymer or whatever is the new hotness ;-)

**Comment by zoffixznet** [comment]
> Also the 6 is falling off the edge of the download button at smaller window widths. 

Fixed! Thanks :)

**Comment by asb-capfan** [comment]
I like it. Please merge it.
We will not find a consensus based on personal taste.
So let's consider the technical view.
As already pointed out by jonathanstowe, this PR could encourage new contributions.

Regarding the question how to attract 9 year  old programmers without lollipop colors: as this specific target group is so big (irony), I guess a single landingpage will do.
Also, "yet another X" will match anything. Yet another fancy design. Yet another Dancer 2 web site. It boils down to personal taste.

**Pull request merged**
