### PR TITLE
update debian informations

### PR DESCRIPTION
**Pull request by eiro**

### CODE REVIEW

**Comment by lizmat** [comment]
OOC, why the change from "rakudo" to "perl6" ?

**Comment by AlexDaniel** [comment]
FWIW debian has both `perl6` and `rakudo` packages (I think `perl6` is just a metapackage that depends on `rakudo`).

**Comment by eiro** [comment]
hello Liz,

On Tue, Nov 27, 2018 at 05:39:24AM -0800, Elizabeth Mattijsen wrote:
> OOC, why the change from "rakudo" to "perl6" ?

i'm sorry i didn't explain it in the PR comment.

that's just a "user perspective" change for me: it is simpler for the
user to install perl6 that provide perl6 that explaining that "perl6 is
actually a spec with many implementations but the one you probably want
is rakudo because it is the one supported by the community".

    aptitude install perl6 perl6-zef

and have fun :)

regards

**Comment by AlexDaniel** [comment]
Ah yeah, there's also no `rakudo` binary so IMO this change makes sense.

**Comment by eiro** [comment]
On Tue, Nov 27, 2018 at 05:41:38AM -0800, Aleks-Daniel Jakimenko-Aleksejev wrote:
> FWIW debian has both `perl6` and `rakudo` packages (I think `perl6` is
> just a metapackage that depends on `rakudo`).

actually, in stretch, perl6 is a package that depends on

rakudo, perl6-tap-harness, perl6-zef

so installing perl6 provide zef which is probably what's expected by a
newcommer.

marc

**Comment by AlexDaniel** [comment]
Thanks!

I tweaked it a bit here: https://github.com/perl6/perl6.org/commit/850c26433b0d650496a8a60693708181314e90af

**Comment by AlexDaniel** [comment]
@eiro oh! I didn't know that Debian started providing zef… maybe this should be mentioned somewhere. Please also see this ticket: https://github.com/perl6/user-experience/issues/29

**Comment by eiro** [comment]
hello,

On Tue, Nov 27, 2018 at 01:57:57PM +0000, Aleks-Daniel Jakimenko-Aleksejev wrote:
> @eiro oh! I didn't know that Debian started providing zef… maybe this should be mentioned somewhere. Please also see this ticket: https://github.com/perl6/user-experience/issues/29

cool! but wait ... i said "stretch" which is the current stable but i
use buster (the future one) ... FIY

marc

**Comment by robertlemmen** [comment]
yeah, we do have zef now, but it still has a few rough edges, most notably if you install a perl module that also has an executable (e.g. prove6), then that does not end up in a PATH you normally find executables in. the idea is that we would modify zef to symlink in /usr/bin or so, but that work has not yet happened.

there is also a first module package (perl6-readline) in the works. based on this we want to change some of the packaging infrastructure, and then go nito full-blown moduel packaging mode :)

**Comment by eiro** [comment]
hello,

On Tue, Nov 27, 2018 at 06:40:02AM -0800, Robert Lemmen wrote:
> prove6), then that does not end up in a PATH you normally find
> executables in. the idea is that we would modify zef to symlink in
> /usr/bin or so, but that work has not yet happened.

what about non-root users? why not steal the perl5 -Mlocal::lib strategy?

PERL_MB_OPT="--install_base \"/home/mc/tmp/demobase\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/home/mc/tmp/demobase"; export PERL_MM_OPT;

when i used zef from the sources, the final target used to be
`~/.perl6/bin` but now i use the debian package and

    locate -r '/cro$'

outputs

    /home/mc/.zef/store/cro-0.7.6.tar.gz/cro-0.7.6/bin/cro
    /home/mc/.zef/store/cro.git/fb251c594c3ed04cd9a16c1b045f4380abb40549/bin/cro
    /home/mc/.zef/tmp/cro.git/bin/cro
    /home/mc/.zef/tmp/cro.git/bin/cro

but none of them have a shebang nor are executable

    find $( locate -r '/cro$' ) -executable

remains empty.

regards
marc

**Comment by robertlemmen** [comment]
@eiro sorry, I wasn very inprecise above. I did not mean installation through zef as a normal user, but apt-get install of a perl6-* package that contains executables.

The calling zef as a user case you describe should work as expected, what you are showing looks like a bug to me. it should work just like a zef you installed from source...

do you want to report a debian bug for it, or shall I?

**Comment by eiro** [comment]
hello,

> The calling zef as a user case you describe should work as expected, what you are showing looks like a bug to me. it should work just like a zef you installed from source...
> do you want to report a debian bug for it, or shall I?

i will... and maybe with a patch provided.

regards

marc

**Pull request merged**
