### PR TITLE
Add "Getting Involved" Section

### PR DESCRIPTION
**Pull request by WildYorkies**
Looking for feedback on this addition. Think I covered the main areas

### CODE REVIEW

**Comment by zoffixznet** [comment]
Personally I disagree with the proposed `Help us write tests` section. We (or at least I) don't welcome newcomers writing specification tests. You need at least basic understanding of Perl 6 to write a coherent test, and much more knowledge is needed to cover all the edge cases and discern when the behaviour is actually a bug and isn't wanted. Other nitpicks on that section: it doesn't say which tests need to be written and our Test.pm6 routines aren't the `Test Anything Protocol`; they merely generate output that conforms to the protocol and the user doesn't need to know anything about the protocol itself.

Also, the single-column layout looks bad and is hard to read. It'd be better to leave the outer `Getting Involved` panel as one-column, but break up individual sections inside into 2- or 3-column layout (without any extra panels)

z

**Comment by WildYorkies** [comment]
Would it help to break it into two sections like 

- "I am learning"
-- "Write about your experience"
-- "Feedback on Docs"
- "I already know the language"
-- "Help write tests"
-- "Contribute to eco"
-- "hack on compiler"

That way I could do a two column layout as well.

Regarding the actual content, I do think there should be more details on how exactly to start out. For example, look for issues marked with the LHF label, etc. And on tests, maybe it would be worthwhile to also start using some beginner-friendly labels on issues too?

**Comment by WildYorkies** [comment]
The sizing is finnicky, but how's this layout? 

2017-03-03 09_28_43-perl 6 community

**Comment by zoffixznet** [comment]
That's great. I think the sizing can be helped if you use `col-sm-5` on the left column and  `col-sm-7` on the right one. This will make them more equal in length and align with the columns in the previous panel

**Comment by zoffixznet** [comment]
Thanks.

**Pull request merged**
