### PR TITLE
clarify quick install instructions

### PR DESCRIPTION
**Pull request by tbrowder**

### CODE REVIEW

**Comment by zoffixznet** [comment]
:-1: on having long instructions on that page, especially ones that suggest running `rm -fr` as root.

Reading that text I ask myself: "what the hell is $PREFIX and why do I need to think about it?"

**Comment by stmuk** [comment]
The target audience was intended to be fairly UNIX savvy (familiar with source builds) and fairly ADHD (much as myself!) in avoiding long READMEs. It's a "quickstart". I don't see the point in telling them to delete the directory if it exists already. It's obvious.  Neither do we need to try and explain UNIX perms or anything else. People who aren't familiar with source installs should use the star binaries.

**Comment by coke** [comment]
I agree with @zoffixznet  & @stmuk

**Comment by JJ** [comment]
This should be either updated or closed...

**Pull request closed without merging**
