### PR TITLE
Give Perl 6 a more adult intro

### PR DESCRIPTION
**Pull request by lizmat**
- de-emphasize being the sister of Perl 5
- emphasize being part of the Perl community
- emphasize continued development, rather than being just new

### CODE REVIEW

**Comment by cygx** [comment]
I never was too fond of that introduction: While I'm ok with whimsical, it was a bit too bombastic ('world-famous') and fluffy ('hight ideals of the Perl community' - what does that mean?) for my taste.

I also disagree with your edit removing any mention of Perl 5: The relationship between the languages should be addressed somehow.

This is what I came up with just now:

> Hi, my name is Camelia. I'm the spokesbug for Perl 6, the newest member of the Perl family of programming languages. Like her famous big sister Perl 5, Perl 6 has been developed by a team of dedicated and enthusiastic volunteers, and continues to be actively developed. You can help too! The only requirement is that you know how to be nice to all kinds of people (and butterflies). Go to #perl6 (irc.freenode.net) and someone will be glad to help you get started.

**Comment by lizmat** [comment]
> I also disagree with your edit removing any mention of Perl 5

@cygx: I believe the current consensus in the Perl 5 community is that Perl 6 is a *different* language.   Therefore, it doesn't make sense to mention Perl 5 to a newbie, who is not aware of the Perl 6 lineage.  Which is why I removed it and emphasized the community aspect by linking to the Perl Foundation.

**Comment by cygx** [comment]
@lizmat Say I have a vague idea that there is an old programming language called Perl, and perhaps even that people used to write CGI/sysadmin/etc scripts with it. The introduction should help me fit Perl 6 into that preexisting understanding.

So lets's compare the information content of the suggested phrasings:

**Original one:**

  - Perl 6 is a sister of Perl 5
  - it intends to carry forward some high ideals, whatever that means
  - it is currently being developed by volunteers
  - how to get involved


**Your proposal:**

  - Perl 6 intends to carry forward some high ideals, whatever that means
  - the Perl community is associated with the Perl foundation
  - it has been and continues to be developed by volunteers
  - how to get involved


**My Proposal:**

  - Perl 6 is a member of the Perl family of programming languages
  - it is a sister of Perl 5
  - it has been and continues to be actively developed by volunteers
  - how to get involved

The question we need to ask is, which of these pieces of information are most useful to that newcomer?

**Comment by lizmat** [comment]
@cygx: if people *are* interested in what the Perl community is about, they will follow the link and wind up at the Perl Foundation home page, that lists both Perl 5 and Perl 6.  I posit that for a "blank slate" visitor to `https://perl6.org`, the stating the link with Perl 5 is immaterial.  It is of historical importance, yes.  People will find that out quickly enough when the follow the link to the Perl Foundation.

**Comment by AlexDaniel** [comment]
I'm OK with that PR. However, can't we replace

> intends to carry forward the high ideals of

With something that doesn't have hidden notes of historical baggage? Like “Perl 6 is a brand new language that addresses many typical issues in programming” or something with a similar idea but worded better.

**Comment by lizmat** [comment]
@AlexDaniel: I don't think using the word `issues` in what is a first intro, would be a good sign.  Haven't been able to come up with a phrasing that feels right to what you want to convey yet.

**Comment by Altai-man** [comment]
s/issues/questions/ or s/issues/tasks/
>a language that proposes/presents $insert-adjective-here solutions to programming tasks/questions

maybe?

I think we may still want to empathize that Perl 6 is not "just yet another programming language we have tons of them already with variables, loops etc", but show its a bit distinctive approach in some areas. While we have a small feature list below, intro should probably indicate that.

**Comment by AlexDaniel** [comment]
> I don't think using the word `issues` in what is a first intro, would be a good sign. Haven't been able to come up with a phrasing that feels right to what you want to convey yet.

What about something like “Perl 6 is a brand new language that brings fun back into programming.” ?

**Comment by masak** [comment]
I'm not sure "brand new" is the mental box we want to put Perl 6 in for people. Even by the most conservative estimates, Perl 6 is 3.5 years old.

**Comment by lizmat** [comment]
Going to merge it now.  Jonathan said in a private /msg while on holiday somewhere in PL that he'd be ok with it going in like this, and with potential followup tweaks later.

**Comment by AlexDaniel** [comment]
> Perl 6 is 3.5 years old.

And that's pretty young compared to many programming languages.

**Comment by JJ** [comment]
Thanks!

I'm not so sure this is deployed automatically. I think I have the privs to
deploy it. Should I proceed?

**Comment by lizmat** [comment]
Please do!

**Comment by rba** [comment]
Change is online now.

Realised that there are some dependencies missing for the automatic update. Should be fixed.
Be aware this runs now on the new server from @niner and not on @timo 's server any more.

**Comment by Altai-man** [comment]
@rba

Not to brag about it, but I own that server, thus with this info a question is: is there any sense in this temporary backup anymore? I see from what it hosts only alerts.perl6.org still points to this IP, but it is mis-configured. Not sure if something else is there besides perl6.org, modules, docs, rakudo.org - all of those are moved now.

**Comment by JJ** [comment]
Did docs move?

**Comment by Altai-man** [comment]
`ping` for all those (except `alerts.perl6.org`) returns me some different IPs, so I don't see how not.

**Comment by JJ** [comment]
That must have happened sometime between yesterday and today. So how's
documentation deployed now?

**Comment by JJ** [comment]
I think that's the CDN address. The content is still hosted in the same
place.

**Comment by rba** [comment]
@JJ is right, this is the cloudflare CDN you see when you ping.

So far I was only able to migrate perl6.org/www.perl6.org and no other subdomains. All of them have a different setup and I‘m still learning to set them up one-by-one.

On your server @Altai-man is still the production setup of docs.perl6.org, modules.perl6.org and rakudo.org. Please don‘t shut down the server yet. These three domains are the next to migrate on my list (see https://github.com/perl6/problem-solving/issues/68).

**Comment by JJ** [comment]
In that order?

**Comment by rba** [comment]
What’s your wish?

**Comment by JJ** [comment]
Nothing specific, but please try and coordinate with me when you decide to
migrate docs. Also, if you have a time line for that we might try and
deploy the new doc site with @antoniogamiz to minimize disruption.

**Comment by rba** [comment]
As we leave the topic of this PR, I've open an issue [doc/issues/2929](https://github.com/perl6/doc/issues/2929)

**Pull request merged**
