### PR TITLE
Update fetch-recent-blog-posts.pl

### PR DESCRIPTION
**Pull request by ccworld1000**
Perl should keep the general environment variable

### CODE REVIEW

**Comment by ccworld1000** [comment]
First, set the corresponding environment variables

**Comment by zoffixznet** [comment]
What exactly is the purpose of this change?

Don't merge this as this would break the updater. The required modules aren't installed in env perl.

**Comment by ccworld1000** [comment]
The environment variables can be set up by the corresponding machine. Others will make mistakes directly.

**Comment by ccworld1000** [comment]
https://github.com/ccworld1000/perl6.org/blob/master/fetch-recent-blog-posts.pl

**Comment by ccworld1000** [comment]
The typical practice should be like the above
or #!/usr/bin/env perl

The original practice can only be a specific relative path, which should be the Linux system. There may be other Linux, Unix, or maosx environments

**Comment by ccworld1000** [comment]
or #!/usr/bin/perl

**Comment by zoffixznet** [comment]
👍 Thanks!

**Pull request merged**
